/**
* Project Clearwater - IMS in the Cloud
* Copyright (C) 2014 Metaswitch Networks Ltd
*
* This program is free software: you can redistribute it and/or modify it
* under the terms of the GNU General Public License as published by the
* Free Software Foundation, either version 3 of the License, or (at your
* option) any later version, along with the "Special Exception" for use of
* the program along with SSL, set forth below. This program is distributed
* in the hope that it will be useful, but WITHOUT ANY WARRANTY;
* without even the implied warranty of MERCHANTABILITY or FITNESS FOR
* A PARTICULAR PURPOSE. See the GNU General Public License for more
* details. You should have received a copy of the GNU General Public
* License along with this program. If not, see
* <http://www.gnu.org/licenses/>.
*
* The author can be reached by email at clearwater@metaswitch.com or by
* post at Metaswitch Networks Ltd, 100 Church St, Enfield EN2 6BQ, UK
*
* Special Exception
* Metaswitch Networks Ltd grants you permission to copy, modify,
* propagate, and distribute a work formed by combining OpenSSL with The
* Software, or a work derivative of such a combination, even if such
* copying, modification, propagation, or distribution would otherwise
* violate the terms of the GPL. You must comply with the GPL in all
* respects for all of the code used other than OpenSSL.
* "OpenSSL" means OpenSSL toolkit software distributed by the OpenSSL
* Project and licensed under the OpenSSL Licenses, or a work based on such
* software and licensed under the OpenSSL Licenses.
* "OpenSSL Licenses" means the OpenSSL License and Original SSLeay License
* under which the OpenSSL Project distributes the OpenSSL toolkit software,
* as those licenses appear in the file LICENSE-OPENSSL.
*/

/*
 *  Note: this file originally auto-generated by mib2c using
 *         : mib2c.array-user.conf 15997 2007-03-25 22:28:35Z dts12 $
 *
 *  $Id:$
 */

#ifndef ALARM_ACTIVE_TABLE_HPP
#define ALARM_ACTIVE_TABLE_HPP

#include <alarm_table_defs.hpp>
#include "alarm_trap_sender.hpp"
#include "oid_definitions.hpp"
#ifdef __cplusplus
extern "C" {
#endif

#include <string>

typedef struct alarmActiveTable_context_s {
    netsnmp_index _index; /** THIS MUST BE FIRST!!! */

    AlarmTableDef* _alarm_table_def;

} alarmActiveTable_context;

// This structure is defined to comply with the syntax as
// outlined in RFC 2579 under DateAndTime
typedef struct SNMPDateTime {
    uint16_t year;
    uint8_t month;
    uint8_t day;
    uint8_t hour;
    uint8_t minute;
    uint8_t second;
    uint8_t decisecond;
    uint8_t direction;
    uint8_t timegeozone;
    uint8_t mintimezone;
} alarmActiveTable_SNMPDateTime;

int init_alarmActiveTable(std::string);
int alarmActiveTable_get_value(netsnmp_request_info*, netsnmp_index*, netsnmp_table_request_info*);
void alarmActiveTable_trap_handler(AlarmTableDef&);
void alarmActiveTable_create_row(AlarmTableDef&);
void alarmActiveTable_delete_row(AlarmTableDef&);
int alarmActiveTable_index_to_oid(char*, alarmActiveTable_SNMPDateTime, unsigned long, netsnmp_index*);
alarmActiveTable_SNMPDateTime alarm_time_issued(void);

/*************************************************************
 *
 *  column number definitions for table alarmActiveTable
 */
#define COLUMN_ALARMLISTNAME 1
#define COLUMN_ALARMACTIVEDATEANDTIME 2
#define COLUMN_ALARMACTIVEINDEX 3
#define COLUMN_ALARMACTIVEENGINEID 4
#define COLUMN_ALARMACTIVEENGINEADDRESSTYPE 5
#define COLUMN_ALARMACTIVEENGINEADDRESS 6
#define COLUMN_ALARMACTIVECONTEXTNAME 7
#define COLUMN_ALARMACTIVEVARIABLES 8
#define COLUMN_ALARMACTIVENOTIFICATIONID 9
#define COLUMN_ALARMACTIVERESOURCEID 10
#define COLUMN_ALARMACTIVEDESCRIPTION 11
#define COLUMN_ALARMACTIVELOGPOINTER 12
#define COLUMN_ALARMACTIVEMODELPOINTER 13
#define COLUMN_ALARMACTIVESPECIFICPOINTER 14
#define alarmActiveTable_COL_MIN 4
#define alarmActiveTable_COL_MAX 14

#define ROWSTATUS_ACTIVE 1

#define ITUALARMTABLEROW_INDEX 13
#define ITUALARMTABLEROW_SEVERITY 14

#ifdef __cplusplus
}
#endif

#endif /** ALARMACTIVETABLE_HPP */
