#!/bin/bash
# @file clearwater-snmp-alarm-agent
#
# Copyright (C) Metaswitch Networks 2016
# If license terms are provided to you in a COPYING file in the root directory
# of the source code repository by which you are accessing this code, then
# the license outlined in that COPYING file applies to your use.
# Otherwise no rights are granted except for those provided to you by
# Metaswitch Networks in a separate written agreement.

SERVICE=clearwater-snmp-alarm-agent

# Restart the alarm agent.  The alarm agent is managed either by systemctl (on
# centos) or upstart (on ubuntu). Detect which one is installed and restart the
# agent appropriately.
if which systemctl >/dev/null 2>&1; then
  systemctl restart $SERVICE
else
  restart $SERVICE
fi

exit 0
