#/bin/sh

# @file clearwater-snmp-alarm-agent.postinst
#
# Copyright (C) Metaswitch Networks 2015
# If license terms are provided to you in a COPYING file in the root directory
# of the source code repository by which you are accessing this code, then
# the license outlined in that COPYING file applies to your use.
# Otherwise no rights are granted except for those provided to you by
# Metaswitch Networks in a separate written agreement.

#
# see: dh_installdeb(1)

rm -f /etc/monit/conf.d/alarm_agent.monit
# Force monit to reload its configuration
reload clearwater-monit || true

# Trigger an snmpd restart to unload the sub-agent
service snmpd stop || true
